const employees = [

{
    HoTen: "Nguyễn Văn An",
    NgaySinh: "1995-03-15",
    SoDienThoai: "0901234567",
    NgayCap: "2020-05-12",
    DcEmail: "an.nguyen@company.com",
    NoiCap: "Cục CSQLHC về TTXH",
    GioiTinh: "Nam",
    SoCccd: "001095123456",
    QuocTich: "Việt Nam",
    MaNhanVien: "EMP001",
    Level: "Junior Developer",
    PhongBan: "Phát triển phần mềm",
    DCTtru: "Ba Đình, Hà Nội",
    DCHtai: "Nam Từ Liêm, Hà Nội",
    NgLienHe: "Nguyễn Thị Lan",
    SDTNgLienHe: "0911222333",
    QuanHe: "Mẹ",
    DCNgLienHe: "Ba Đình, Hà Nội",
    TenDangNhap: "nguyenvanan",
    EmailDangNhap: "an.nguyen@company.com",
    HocVan: "Đại học",
    NgoaiNgu: "Tiếng Anh (IELTS 6.5)",
    KyNang: "HTML, CSS, JavaScript",
    GhiChu: "",
    Avatar: "assets/avatar/EMP001.jpg"
},

{
    HoTen: "Trần Thị Bình",
    NgaySinh: "1997-07-22",
    SoDienThoai: "0902345678",
    NgayCap: "2021-03-18",
    DcEmail: "binh.tran@company.com",
    NoiCap: "Công an TP Hà Nội",
    GioiTinh: "Nữ",
    SoCccd: "001097654321",
    QuocTich: "Việt Nam",
    MaNhanVien: "EMP002",
    Level: "Tester",
    PhongBan: "QA/QC",
    DCTtru: "Hải Châu, Đà Nẵng",
    DCHtai: "Cầu Giấy, Hà Nội",
    NgLienHe: "Trần Văn Minh",
    SDTNgLienHe: "0912333444",
    QuanHe: "Bố",
    DCNgLienHe: "Hải Châu, Đà Nẵng",
    TenDangNhap: "tranthibinh",
    EmailDangNhap: "binh.tran@company.com",
    HocVan: "Đại học",
    NgoaiNgu: "Tiếng Anh (TOEIC 850)",
    KyNang: "Manual Test, SQL, Postman",
    GhiChu: "",
    Avatar: "assets/avatar/EMP002.jpg"
},

{
    HoTen: "Lê Minh Cường",
    NgaySinh: "1993-11-08",
    SoDienThoai: "0903456789",
    NgayCap: "2019-09-20",
    DcEmail: "cuong.le@company.com",
    NoiCap: "Công an TP Hồ Chí Minh",
    GioiTinh: "Nam",
    SoCccd: "001093987654",
    QuocTich: "Việt Nam",
    MaNhanVien: "EMP003",
    Level: "Senior Developer",
    PhongBan: "Phát triển phần mềm",
    DCTtru: "Quận 1, TP Hồ Chí Minh",
    DCHtai: "Thanh Xuân, Hà Nội",
    NgLienHe: "Lê Thị Hoa",
    SDTNgLienHe: "0913444555",
    QuanHe: "Vợ",
    DCNgLienHe: "Thanh Xuân, Hà Nội",
    TenDangNhap: "leminhcuong",
    EmailDangNhap: "cuong.le@company.com",
    HocVan: "Đại học",
    NgoaiNgu: "Tiếng Anh, Tiếng Nhật N3",
    KyNang: "Java, Spring Boot, SQL Server",
    GhiChu: "Team Leader dự án HRM",
    Avatar: "assets/avatar/EMP003.jpg"
},

{
    HoTen: "Phạm Thu Hà",
    NgaySinh: "1998-01-30",
    SoDienThoai: "0904567890",
    NgayCap: "2022-01-12",
    DcEmail: "ha.pham@company.com",
    NoiCap: "Công an TP Hải Phòng",
    GioiTinh: "Nữ",
    SoCccd: "001098112233",
    QuocTich: "Việt Nam",
    MaNhanVien: "EMP004",
    Level: "Business Analyst",
    PhongBan: "Phân tích nghiệp vụ",
    DCTtru: "Lê Chân, Hải Phòng",
    DCHtai: "Đống Đa, Hà Nội",
    NgLienHe: "Phạm Văn Long",
    SDTNgLienHe: "0914555666",
    QuanHe: "Anh trai",
    DCNgLienHe: "Lê Chân, Hải Phòng",
    TenDangNhap: "phamthuha",
    EmailDangNhap: "ha.pham@company.com",
    HocVan: "Đại học",
    NgoaiNgu: "Tiếng Anh",
    KyNang: "Agile, UML, Jira, Figma",
    GhiChu: "",
    Avatar: "assets/avatar/EMP004.jpg"
},

{
    HoTen: "Hoàng Quốc Việt",
    NgaySinh: "1991-09-18",
    SoDienThoai: "0905678901",
    NgayCap: "2018-06-10",
    DcEmail: "viet.hoang@company.com",
    NoiCap: "Cục CSQLHC về TTXH",
    GioiTinh: "Nam",
    SoCccd: "001091223344",
    QuocTich: "Việt Nam",
    MaNhanVien: "EMP005",
    Level: "Project Manager",
    PhongBan: "Quản lý dự án",
    DCTtru: "Ninh Kiều, Cần Thơ",
    DCHtai: "Tây Hồ, Hà Nội",
    NgLienHe: "Hoàng Thị Mai",
    SDTNgLienHe: "0915666777",
    QuanHe: "Vợ",
    DCNgLienHe: "Tây Hồ, Hà Nội",
    TenDangNhap: "hoangquocviet",
    EmailDangNhap: "viet.hoang@company.com",
    HocVan: "Thạc sĩ",
    NgoaiNgu: "Tiếng Anh (IELTS 7.5)",
    KyNang: "Project Management, Scrum, Power BI",
    GhiChu: "Quản lý nhiều dự án nội bộ",
    Avatar: "assets/avatar/EMP005.jpg"
}

];